import "./Table.css";
export default function Table(props) {
  console.log(props.myparam);
  return (
    <div className="table">
      <table>
        <thead>
          <tr>
            <th>Field</th>
            <th>value</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>name:</td>
            <td>{props.myparam.name}</td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>symbol:</td>
            <td>{props.myparam.symbol}</td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>id:</td>
            <td>{props.myparam.id}</td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>current_price:</td>
            <td>{props.myparam.current_price}</td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>market_cap_rank:</td>
            <td>{props.myparam.market_cap_rank}</td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>market_cap:</td>
            <td>{props.myparam.market_cap}</td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>total_volume:</td>
            <td>
              <p>{props.myparam.total_volume}</p>
            </td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>price_change_24h:</td>
            <td>{props.myparam.price_change_24h}</td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>price_change_percentage_24h:</td>
            <td>{props.myparam.price_change_percentage_24h}</td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>circulating_supply:</td>
            <td>{props.myparam.circulating_supply}</td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>total_supply:</td>
            <td>{props.myparam.total_supply}</td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>last_updated:</td>
            <td>{props.myparam.last_updated}</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}
